### ISSUE TITLE
Update 0.4

### ISSUE THREAD

**Issue by batasu** [farhansadik/gitman#1]
1. It would better, if it has a **custom commit** system for specific file. 
2. Branch Switch/View Branch
3. View specific file using log `git show <hash>:/path/to/file`
4. View Remote 
5. Git Repository Info
6. Tag 
7. Checkout

Also add `pause` function in every operation

**Comment by farhansadik** [comment]
**Pause Function**
```bash
function pause(){
    # Purpose: Display pause prompt
    local message="$@"
    [ -z $message ] && message="Press [Enter] key to continue..."
    read -p "$message" readEnterKey
}
```
