### ISSUE TITLE
view repository info

### ISSUE THREAD

**Issue by farhansadik** [farhansadik/gitman#4]
### we should include those info
1. remote 
2. branch 
3. git remote show origin
4. git config --get remote.origin.url
5. git remote -v
6. git version

https://git-scm.com/docs/git

**Comment by farhansadik** [comment]
To obtain only the remote URL:
```
git config --get remote.origin.url
```
If you require full output, and you are on a network that can reach the remote repo where the origin resides:
```
git remote show origin
```
When using git clone (from GitHub, or any source repository for that matter) the default name for the source of the clone is "origin". Using git remote show will display the information about this remote name. The first few lines should show:
```
C:\Users\jaredpar\VsVim> git remote show origin
* remote origin
  Fetch URL: git@github.com:jaredpar/VsVim.git
  Push  URL: git@github.com:jaredpar/VsVim.git
  HEAD branch: master
  Remote branches:
```
https://stackoverflow.com/questions/4089430/how-to-determine-the-url-that-a-local-git-repository-was-originally-cloned-from

**Comment by batasu** [comment]
Fixed! 
0.4.55
